In [7]:
import pandas as pd 
from sklearn import tree
import matplotlib
import matplotlib.pyplot as plt
import openpyxl
datos = pd.read_csv("../databases/full_database.csv")

In [8]:
datos.head()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
0,1,3,1,1,3,4,2,1,52.09302,25,9,2020,3
1,1,2,1,3,3,2,2,1,65.11628,25,9,2020,3
2,1,2,1,3,3,2,2,1,73.64341,24,9,2020,3
3,2,5,1,1,3,1,1,3,66.66667,9,9,2020,3
4,2,4,2,3,2,2,1,1,37.50000,24,9,2020,3

In [9]:
#Filtrar por ent
datos = datos[datos['ent'] == 23]

In [10]:
datos = datos[["eda7c", "ano"]]

In [11]:
datos_agrupados = datos.groupby(["ano", "eda7c"]).value_counts()
datos_agrupados = datos_agrupados.to_frame(name = "total").reset_index()#.drop("total", axis = 1)
datos_agrupados = datos_agrupados.pivot(index = "ano",columns= "eda7c",values= "total").fillna(0)

In [12]:
datos_agrupados.apply(lambda x: 100 * x/x.sum(), axis = 1)

eda7c         1          2          3          4          5         6
ano
2005   8.192367  30.085279  30.735356  19.956662   8.283238  2.747099
2006   8.925391  30.166898  29.619368  20.186028   8.212943  2.889373
2007   9.107856  30.672437  27.869507  21.171771   8.535286  2.643142
2008   9.138399  31.336630  27.087832  20.742495   8.831929  2.862715
2009   8.095799  31.142521  25.740086  21.751080  10.098155  3.172360
2010   7.152919  30.247300  25.755204  22.405697  10.658945  3.779934
2011   7.310178  31.252019  24.386107  22.358643  10.767367  3.925687
2012   7.033905  29.858532  25.053347  23.662373  10.795859  3.595985
2013   6.604988  28.576026  27.457763  22.936444  10.539019  3.885760
2014   5.687394  29.490789  28.300217  22.918510   9.999196  3.603893
2015   5.516014  28.995471  27.588159  23.188289  10.894533  3.817535
2016   5.580053  29.239157  27.427243  21.502445  11.873647  4.377455
2017   5.299803  28.464941  28.571429  21.748034  11.623526  4.292267
2018   5.182500  27.230782  27.889923  21.463294  13.298179  4.935322
2019   4.736301  26.694078  25.776864  22.448011  14.841464  5.503281
2020   4.493526  26.184311  25.894897  23.229246  15.460777  4.737243
2021   4.268236  26.039040  25.347903  23.592043  15.345101  5.407677
2022   4.042227  25.877470  25.642876  22.845800  15.997474  5.594153
2023   4.777796  24.890119  24.751750  23.262250  15.879863  6.438222
2024   4.537773  23.947947  26.111205  23.026872  15.869528  6.506676
2025   4.346264  23.599138  28.439296  23.446480  14.538434  5.630388