In [1]:
import pandas as pd 
from sklearn import tree
import matplotlib
import matplotlib.pyplot as plt
import openpyxl
datos = pd.read_csv("../databases/full_database.csv")

In [2]:
datos.head()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
0,1,3,1,1,3,4,2,1,52.09302,25,9,2020,3
1,1,2,1,3,3,2,2,1,65.11628,25,9,2020,3
2,1,2,1,3,3,2,2,1,73.64341,24,9,2020,3
3,2,5,1,1,3,1,1,3,66.66667,9,9,2020,3
4,2,4,2,3,2,2,1,1,37.50000,24,9,2020,3

In [3]:
datos.describe()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
count,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06
mean,1.741002e+00,3.320203e+00,1.400798e+00,1.665227e+00,2.728614e+00,2.346756e+00,1.544698e+00,1.407535e+00,4.356658e+01,4.404573e+01,1.203602e+01,2.015013e+03,2.502610e+00
std,8.422604e-01,1.315314e+00,4.900603e-01,8.845338e-01,4.446748e-01,1.543471e+00,4.979983e-01,7.783123e-01,6.648547e+01,1.667100e+01,7.111387e+00,6.218843e+00,1.124765e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,7.750000e-03,1.000000e+00,5.000000e+00,2.005000e+03,1.000000e+00
25%,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.875000e+01,3.600000e+01,5.000000e+00,2.009000e+03,1.000000e+00
50%,2.000000e+00,3.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,3.000000e+01,4.700000e+01,9.000000e+00,2.015000e+03,3.000000e+00
75%,2.000000e+00,4.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,2.000000e+00,1.000000e+00,5.000000e+01,5.100000e+01,1.900000e+01,2.021000e+03,4.000000e+00
max,4.000000e+00,6.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,8.000000e+00,2.000000e+00,3.000000e+00,2.990033e+04,1.680000e+02,2.300000e+01,2.025000e+03,4.000000e+00

In [4]:
#Filtrar por ent
datos = datos[datos['ent'] == 19]

In [5]:
datos = datos[["hrsocup", "ano"]]

In [6]:
datos_agrupados = datos.groupby(["ano", "hrsocup"]).value_counts()
datos_agrupados = datos_agrupados.to_frame(name = "total").reset_index()#.drop("total", axis = 1)
datos_agrupados = datos_agrupados.pivot(index = "ano",columns= "hrsocup",values= "total").fillna(0)

In [7]:
datos_agrupados.apply(lambda x: 100 * x/x.sum(), axis = 1)

hrsocup,1,2,3,4,5,6,7,8,9,10,...,120,122,123,126,132,133,140,144,147,168
ano,,,,,,,,,,,,,,,,,,,,,
2005,0.132059,0.301093,0.269399,0.485975,0.348635,0.728963,0.237705,0.565211,0.332787,0.596905,...,0.000000,0.000000,0.005282,0.026412,0.000000,0.000000,0.005282,0.000000,0.000000,0.010565
2006,0.135663,0.287606,0.276753,0.477534,0.249620,0.694595,0.179075,0.689169,0.412416,0.591491,...,0.005427,0.000000,0.000000,0.010853,0.000000,0.000000,0.000000,0.000000,0.005427,0.005427
2007,0.091128,0.289467,0.359153,0.343072,0.359153,0.761190,0.262664,0.739748,0.461002,0.761190,...,0.005360,0.000000,0.000000,0.026802,0.000000,0.005360,0.000000,0.000000,0.000000,0.032163
2008,0.114574,0.297892,0.309349,0.555683,0.406737,0.802016,0.246334,0.750458,0.412466,0.721815,...,0.005729,0.000000,0.000000,0.011457,0.000000,0.000000,0.000000,0.000000,0.000000,0.005729
2009,0.098451,0.406931,0.400368,0.708847,0.485692,0.912313,0.354424,0.938567,0.354424,0.741664,...,0.019690,0.006563,0.000000,0.013127,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2010,0.140327,0.360842,0.427665,0.648179,0.454394,1.042432,0.327431,1.029068,0.554627,0.855329,...,0.006682,0.000000,0.000000,0.013365,0.000000,0.000000,0.013365,0.000000,0.000000,0.020047
2011,0.191247,0.441339,0.411916,0.735565,0.433983,0.985656,0.353071,0.809121,0.485473,0.904744,...,0.000000,0.000000,0.000000,0.036778,0.000000,0.007356,0.000000,0.000000,0.000000,0.007356
2012,0.201801,0.403601,0.574356,0.752872,0.450171,1.226327,0.512263,0.993480,0.512263,0.814964,...,0.000000,0.007762,0.000000,0.007762,0.007762,0.000000,0.000000,0.000000,0.000000,0.000000
2013,0.195099,0.468238,0.374590,0.694553,0.530670,1.147183,0.280943,0.936476,0.554081,0.850632,...,0.007804,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.007804,0.000000,0.000000
2014,0.204563,0.385523,0.354052,0.708104,0.361920,0.920535,0.314713,0.833989,0.361920,0.983478,...,0.007868,0.000000,0.000000,0.000000,0.000000,0.000000,0.007868,0.000000,0.000000,0.000000
2015,0.134862,0.329662,0.412078,0.584401,0.359631,0.839140,0.284708,0.734247,0.337154,0.749232,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2016,0.138808,0.350672,0.357978,0.620982,0.452951,0.876680,0.292227,0.810929,0.467563,0.789012,...,0.014611,0.000000,0.000000,0.021917,0.000000,0.000000,0.000000,0.000000,0.000000,0.007306
2017,0.119780,0.207618,0.239559,0.503074,0.351354,0.854428,0.247545,0.790545,0.383295,0.606883,...,0.000000,0.000000,0.000000,0.023956,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2018,0.094899,0.284698,0.292606,0.466588,0.411230,0.695927,0.316331,0.719652,0.363780,0.640569,...,0.007908,0.000000,0.000000,0.007908,0.000000,0.000000,0.007908,0.000000,0.000000,0.000000
2019,0.082138,0.290643,0.290643,0.663423,0.296961,0.732925,0.170595,0.802426,0.379099,0.631832,...,0.006318,0.000000,0.000000,0.012637,0.000000,0.000000,0.000000,0.000000,0.006318,0.000000
2020,0.129930,0.232019,0.315545,0.547564,0.380510,0.686775,0.148492,0.593968,0.436195,0.761021,...,0.000000,0.000000,0.000000,0.037123,0.000000,0.000000,0.000000,0.000000,0.000000,0.009281
2021,0.105343,0.228244,0.327735,0.433078,0.356997,0.807632,0.193129,0.831041,0.444783,0.696436,...,0.011705,0.000000,0.000000,0.000000,0.000000,0.000000,0.005852,0.000000,0.000000,0.000000
2022,0.083003,0.249010,0.312859,0.510790,0.446942,0.766186,0.242625,0.785340,0.389478,0.702337,...,0.012770,0.006385,0.000000,0.025540,0.006385,0.000000,0.000000,0.006385,0.000000,0.000000
2023,0.081637,0.215756,0.285731,0.565631,0.279900,0.728905,0.279900,0.728905,0.443175,0.653099,...,0.005831,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.005831,0.000000,0.005831
2024,0.161319,0.197168,0.304714,0.454084,0.466033,0.609428,0.179244,0.806596,0.274840,0.537731,...,0.011950,0.000000,0.000000,0.011950,0.000000,0.000000,0.005975,0.000000,0.000000,0.011950
2025,0.104924,0.262310,0.359739,0.427190,0.509631,0.779435,0.232332,0.981788,0.404707,0.899348,...,0.000000,0.000000,0.000000,0.007495,0.000000,0.000000,0.014989,0.007495,0.000000,0.000000