In [1]:
import pandas as pd 
from sklearn import tree
import matplotlib
import matplotlib.pyplot as plt
import openpyxl
datos = pd.read_csv("../databases/full_database.csv")

In [2]:
datos.head()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
0,1,3,1,1,3,4,2,1,52.09302,25,9,2020,3
1,1,2,1,3,3,2,2,1,65.11628,25,9,2020,3
2,1,2,1,3,3,2,2,1,73.64341,24,9,2020,3
3,2,5,1,1,3,1,1,3,66.66667,9,9,2020,3
4,2,4,2,3,2,2,1,1,37.50000,24,9,2020,3

In [4]:
#Filtrar por ent
datos = datos[datos['ent'] == 7]

In [5]:
datos = datos[["eda7c", "ano"]]

In [6]:
datos_agrupados = datos.groupby(["ano", "eda7c"]).value_counts()
datos_agrupados = datos_agrupados.to_frame(name = "total").reset_index()#.drop("total", axis = 1)
datos_agrupados = datos_agrupados.pivot(index = "ano",columns= "eda7c",values= "total").fillna(0)

In [7]:
datos_agrupados.apply(lambda x: 100 * x/x.sum(), axis = 1)

eda7c         1          2          3          4          5         6
ano
2005   7.083168  29.931025  28.995888  20.486802   9.968166  3.534952
2006   7.145227  29.350494  28.640616  20.513501  10.289922  4.060240
2007   7.173554  28.178512  28.112397  21.666116  10.300826  4.568595
2008   6.727603  28.227703  27.306943  22.830835  10.303112  4.603804
2009   6.826472  27.651120  27.657634  22.466128  10.995310  4.403335
2010   6.534776  28.377125  26.392581  22.819165  11.233385  4.642968
2011   6.148063  27.643986  26.898573  22.833843  11.697248  4.778287
2012   5.631937  27.358729  27.377649  22.723259  11.957619  4.950807
2013   5.553050  26.670102  27.133930  22.431231  13.019391  5.192295
2014   5.038785  25.428590  27.638355  23.473046  12.945701  5.475523
2015   5.194723  26.093543  27.198132  23.007006  12.901597  5.604999
2016   4.876463  26.319896  26.378414  23.634590  13.348505  5.442133
2017   4.880976  25.885177  27.418817  22.857905  13.129293  5.827832
2018   4.321440  24.914972  27.489163  22.834278  14.464822  5.975325
2019   5.272141  23.414881  25.918200  23.206271  14.861875  7.326633
2020   4.579111  24.727202  25.584567  23.090413  14.848012  7.170694
2021   4.594258  23.657896  26.026450  22.865306  15.496982  7.359108
2022   4.806663  22.051091  26.406403  23.200409  15.727514  7.807920
2023   4.774560  21.417954  25.530382  23.543985  16.215486  8.517634
2024   4.934508  21.319362  25.363182  23.019767  16.723029  8.640152
2025   5.104712  20.811518  25.805477  22.346959  17.297624  8.633709