In [1]:
import pandas as pd 
from sklearn import tree
import matplotlib
import matplotlib.pyplot as plt
import openpyxl
datos = pd.read_csv("../databases/full_database.csv")

In [2]:
datos.head()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
0,1,3,1,1,3,4,2,1,52.09302,25,9,2020,3
1,1,2,1,3,3,2,2,1,65.11628,25,9,2020,3
2,1,2,1,3,3,2,2,1,73.64341,24,9,2020,3
3,2,5,1,1,3,1,1,3,66.66667,9,9,2020,3
4,2,4,2,3,2,2,1,1,37.50000,24,9,2020,3

In [3]:
#Filtrar por ent
datos = datos[datos['ent'] == 5]

In [4]:
datos = datos[["eda7c", "ano"]]

In [5]:
datos_agrupados = datos.groupby(["ano", "eda7c"]).value_counts()
datos_agrupados = datos_agrupados.to_frame(name = "total").reset_index()#.drop("total", axis = 1)
datos_agrupados = datos_agrupados.pivot(index = "ano",columns= "eda7c",values= "total").fillna(0)

In [6]:
datos_agrupados.apply(lambda x: 100 * x/x.sum(), axis = 1)

eda7c         1          2          3          4          5         6
ano
2005   6.376551  27.254612  29.362988  21.675130  10.689722  4.640998
2006   7.256528  26.046083  27.502304  22.470046  11.557604  5.167435
2007   7.181991  26.637685  26.959266  22.093854  11.267270  5.859933
2008   7.002188  26.118405  27.577194  21.225383  12.314612  5.762217
2009   6.116719  25.957617  27.508523  22.728792  12.246808  5.441540
2010   6.267382  25.981502  27.333290  22.456503  11.946187  6.015135
2011   6.480999  25.891463  25.930505  22.768090  12.799323  6.129620
2012   6.538462  26.378205  24.378205  22.410256  13.397436  6.897436
2013   6.312543  26.345270  25.508213  22.531311  13.506199  5.796463
2014   6.124192  25.765524  25.972917  23.801391  12.955959  5.380017
2015   5.986927  25.639929  25.878184  23.507850  13.366730  5.620380
2016   5.944943  24.868543  26.142901  23.235385  14.085988  5.722239
2017   5.821625  24.867805  24.540464  23.941179  14.302261  6.526666
2018   6.486802  24.905036  22.913217  23.726502  15.199182  6.769261
2019   5.649492  24.994453  22.988506  23.862779  15.444015  7.060755
2020   4.893316  25.018510  23.739651  23.712728  16.187656  6.448139
2021   5.156580  25.048214  23.119662  23.376802  16.447791  6.850951
2022   4.878160  25.517589  22.462440  23.241114  17.011726  6.888970
2023   5.064410  25.427296  22.425697  22.396228  17.108697  7.577671
2024   4.857322  25.105108  23.396547  21.106539  17.175060  8.359424
2025   4.503090  24.784723  24.602371  21.765779  17.369061  6.974977