In [1]:
import pandas as pd 
from sklearn import tree
import matplotlib
import matplotlib.pyplot as plt
import openpyxl
datos = pd.read_csv("../databases/full_database.csv")

In [2]:
datos.head()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
0,1,3,1,1,3,4,2,1,52.09302,25,9,2020,3
1,1,2,1,3,3,2,2,1,65.11628,25,9,2020,3
2,1,2,1,3,3,2,2,1,73.64341,24,9,2020,3
3,2,5,1,1,3,1,1,3,66.66667,9,9,2020,3
4,2,4,2,3,2,2,1,1,37.50000,24,9,2020,3

In [3]:
datos.describe()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
count,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06
mean,1.741002e+00,3.320203e+00,1.400798e+00,1.665227e+00,2.728614e+00,2.346756e+00,1.544698e+00,1.407535e+00,4.356658e+01,4.404573e+01,1.203602e+01,2.015013e+03,2.502610e+00
std,8.422604e-01,1.315314e+00,4.900603e-01,8.845338e-01,4.446748e-01,1.543471e+00,4.979983e-01,7.783123e-01,6.648547e+01,1.667100e+01,7.111387e+00,6.218843e+00,1.124765e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,7.750000e-03,1.000000e+00,5.000000e+00,2.005000e+03,1.000000e+00
25%,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.875000e+01,3.600000e+01,5.000000e+00,2.009000e+03,1.000000e+00
50%,2.000000e+00,3.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,3.000000e+01,4.700000e+01,9.000000e+00,2.015000e+03,3.000000e+00
75%,2.000000e+00,4.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,2.000000e+00,1.000000e+00,5.000000e+01,5.100000e+01,1.900000e+01,2.021000e+03,4.000000e+00
max,4.000000e+00,6.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,8.000000e+00,2.000000e+00,3.000000e+00,2.990033e+04,1.680000e+02,2.300000e+01,2.025000e+03,4.000000e+00

In [4]:
#Filtrar por ent
datos = datos[datos['ent'] == 9]

In [5]:
datos = datos[["eda7c", "ano"]]

In [6]:
datos_agrupados = datos.groupby(["ano", "eda7c"]).value_counts()
datos_agrupados = datos_agrupados.to_frame(name = "total").reset_index()#.drop("total", axis = 1)
datos_agrupados = datos_agrupados.pivot(index = "ano",columns= "eda7c",values= "total").fillna(0)

In [7]:
datos_agrupados.apply(lambda x: 100 * x/x.sum(), axis = 1)

eda7c         1          2          3          4          5          6
ano
2005   5.337331  23.958021  27.968516  23.800600  13.043478   5.892054
2006   4.602131  24.469130  28.459155  23.139122  13.330311   6.000151
2007   4.774557  23.396108  27.483004  23.106978  14.354927   6.884426
2008   4.544324  22.447964  27.796666  23.127954  15.225143   6.857948
2009   4.042979  22.509561  27.217265  23.274449  15.962484   6.993262
2010   4.319360  22.269710  27.807584  23.660998  15.313267   6.629081
2011   4.582367  22.998840  26.769142  23.337200  15.322892   6.989559
2012   4.531341  22.482049  24.170386  24.383854  16.640792   7.791578
2013   4.386056  23.057826  24.485363  23.564705  16.147719   8.358332
2014   4.464184  21.307368  25.509623  23.960825  16.137114   8.620886
2015   4.438673  22.039901  23.373864  23.208594  17.058199   9.880770
2016   3.993745  22.687357  23.373030  23.252737  17.021533   9.671599
2017   3.455084  22.384008  23.112043  23.679664  17.287759  10.081441
2018   4.067048  21.595634  21.166840  24.584200  17.892412  10.693867
2019   3.963145  21.330304  21.797299  21.885649  19.260381  11.763221
2020   2.851392  18.316001  25.360617  23.934921  18.517276  11.019792
2021   3.660301  20.196759  24.580440  23.582176  18.012153   9.968171
2022   3.668061  21.283124  23.124128  23.277545  18.507671  10.139470
2023   3.809020  19.613808  24.282502  20.552837  19.798968  11.942865
2024   3.715424  18.975621  22.609001  21.542429  21.354899  11.802625
2025   3.696833  18.550417  23.532529  21.054724  20.617464  12.548032