In [1]:
import pandas as pd 
from sklearn import tree
import matplotlib
import matplotlib.pyplot as plt
import openpyxl
datos = pd.read_csv("../databases/full_database.csv")

In [2]:
datos.head()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
0,1,3,1,1,3,4,2,1,52.09302,25,9,2020,3
1,1,2,1,3,3,2,2,1,65.11628,25,9,2020,3
2,1,2,1,3,3,2,2,1,73.64341,24,9,2020,3
3,2,5,1,1,3,1,1,3,66.66667,9,9,2020,3
4,2,4,2,3,2,2,1,1,37.50000,24,9,2020,3

In [3]:
#Filtrar por ent
datos = datos[datos['ent'] == 5]

In [4]:
datos = datos[["cs_p13_1", "ano"]]

In [5]:
datos_agrupados = datos.groupby(["ano", "cs_p13_1"]).value_counts()
datos_agrupados = datos_agrupados.to_frame(name = "total").reset_index()#.drop("total", axis = 1)
datos_agrupados = datos_agrupados.pivot(index = "ano",columns= "cs_p13_1",values= "total").fillna(0)

In [6]:
datos_agrupados.apply(lambda x: 100 * x/x.sum(), axis = 1)

cs_p13_1          1          2          3         4
ano
2005      55.968374  24.400591  18.377579  1.253455
2006      55.090630  25.867896  17.788018  1.253456
2007      55.073845  26.488804  17.091472  1.345879
2008      55.549477  26.531729  16.599805  1.318989
2009      54.127950  28.143592  16.632128  1.096330
2010      54.310847  27.501455  16.855313  1.332385
2011      55.121031  27.661374  15.786049  1.431546
2012      54.217949  28.570513  15.948718  1.262821
2013      53.401724  28.824973  16.394990  1.378312
2014      53.818470  27.272173  17.561303  1.348054
2015      52.232879  27.350480  18.987110  1.429531
2016      51.617693  28.097742  18.954531  1.330034
2017      51.785265  28.745531  17.928187  1.541018
2018      51.003214  28.869193  18.613032  1.514561
2019      47.281765  29.920561  21.200018  1.597657
2020      47.607189  28.720468  22.104059  1.568284
2021      45.500046  30.021122  23.115070  1.363762
2022      44.805790  30.093441  23.543422  1.557347
2023      45.297634  29.658163  23.377115  1.667088
2024      44.069237  29.841667  24.179265  1.909831
2025      43.252963  30.422450  24.197143  2.127444