In [1]:
import pandas as pd 
from sklearn import tree
import matplotlib
import matplotlib.pyplot as plt
import openpyxl
datos = pd.read_csv("../databases/full_database.csv")

In [2]:
datos.head()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
0,1,3,1,1,3,4,2,1,52.09302,25,9,2020,3
1,1,2,1,3,3,2,2,1,65.11628,25,9,2020,3
2,1,2,1,3,3,2,2,1,73.64341,24,9,2020,3
3,2,5,1,1,3,1,1,3,66.66667,9,9,2020,3
4,2,4,2,3,2,2,1,1,37.50000,24,9,2020,3

In [3]:
datos.describe()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
count,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06,1.502149e+06
mean,1.741002e+00,3.320203e+00,1.400798e+00,1.665227e+00,2.728614e+00,2.346756e+00,1.544698e+00,1.407535e+00,4.356658e+01,4.404573e+01,1.203602e+01,2.015013e+03,2.502610e+00
std,8.422604e-01,1.315314e+00,4.900603e-01,8.845338e-01,4.446748e-01,1.543471e+00,4.979983e-01,7.783123e-01,6.648547e+01,1.667100e+01,7.111387e+00,6.218843e+00,1.124765e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,7.750000e-03,1.000000e+00,5.000000e+00,2.005000e+03,1.000000e+00
25%,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,1.875000e+01,3.600000e+01,5.000000e+00,2.009000e+03,1.000000e+00
50%,2.000000e+00,3.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,3.000000e+01,4.700000e+01,9.000000e+00,2.015000e+03,3.000000e+00
75%,2.000000e+00,4.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,3.000000e+00,2.000000e+00,1.000000e+00,5.000000e+01,5.100000e+01,1.900000e+01,2.021000e+03,4.000000e+00
max,4.000000e+00,6.000000e+00,2.000000e+00,3.000000e+00,3.000000e+00,8.000000e+00,2.000000e+00,3.000000e+00,2.990033e+04,1.680000e+02,2.300000e+01,2.025000e+03,4.000000e+00

In [4]:
#Filtrar por ent
datos = datos[datos['ent'] == 19]

In [5]:
datos = datos[["emp_ppal", "ano"]]

In [6]:
datos_agrupados = datos.groupby(["ano", "emp_ppal"]).value_counts()
datos_agrupados = datos_agrupados.to_frame(name = "total").reset_index()#.drop("total", axis = 1)
datos_agrupados = datos_agrupados.pivot(index = "ano",columns= "emp_ppal",values= "total").fillna(0)

In [7]:
datos_agrupados.apply(lambda x: 100 * x/x.sum(), axis = 1)

emp_ppal          1          2
ano
2005      37.145423  62.854577
2006      37.372477  62.627523
2007      37.823640  62.176360
2008      39.298808  60.701192
2009      42.484904  57.515096
2010      42.753091  57.246909
2011      43.265907  56.734093
2012      45.117976  54.882024
2013      41.556111  58.443889
2014      39.763965  60.236035
2015      40.256237  59.743763
2016      39.793980  60.206020
2017      39.415476  60.584524
2018      41.589561  58.410439
2019      40.317180  59.682820
2020      37.698376  62.301624
2021      37.888453  62.111547
2022      38.430596  61.569404
2023      38.707796  61.292204
2024      37.718827  62.281173
2025      37.817582  62.182418