In [1]:
import pandas as pd 
from sklearn import tree
import matplotlib
import matplotlib.pyplot as plt
import openpyxl
datos = pd.read_csv("../databases/full_database.csv")

In [2]:
datos.head()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
0,1,3,1,1,3,4,2,1,52.09302,25,9,2020,3
1,1,2,1,3,3,2,2,1,65.11628,25,9,2020,3
2,1,2,1,3,3,2,2,1,73.64341,24,9,2020,3
3,2,5,1,1,3,1,1,3,66.66667,9,9,2020,3
4,2,4,2,3,2,2,1,1,37.50000,24,9,2020,3

In [3]:
#Filtrar por ent
datos = datos[datos['ent'] == 5]

In [4]:
datos = datos[["emp_ppal", "ano"]]

In [5]:
datos_agrupados = datos.groupby(["ano", "emp_ppal"]).value_counts()
datos_agrupados = datos_agrupados.to_frame(name = "total").reset_index()#.drop("total", axis = 1)
datos_agrupados = datos_agrupados.pivot(index = "ano",columns= "emp_ppal",values= "total").fillna(0)

In [6]:
datos_agrupados.apply(lambda x: 100 * x/x.sum(), axis = 1)

emp_ppal          1          2
ano
2005      35.437424  64.562576
2006      35.569892  64.430108
2007      36.547165  63.452835
2008      38.402626  61.597374
2009      40.042784  59.957216
2010      39.809844  60.190156
2011      38.508589  61.491411
2012      38.371795  61.628205
2013      36.698345  63.301655
2014      33.249970  66.750030
2015      32.017839  67.982161
2016      33.096195  66.903805
2017      35.498817  64.501183
2018      35.628713  64.371287
2019      34.167665  65.832335
2020      34.058020  65.941980
2021      34.736890  65.263110
2022      33.941004  66.058996
2023      34.962533  65.037467
2024      33.996780  66.003220
2025      33.046297  66.953703