In [1]:
import pandas as pd 
from sklearn import tree
import matplotlib
import matplotlib.pyplot as plt
import openpyxl
datos = pd.read_csv("../databases/full_database.csv")

In [2]:
datos.head()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
0,1,3,1,1,3,4,2,1,52.09302,25,9,2020,3
1,1,2,1,3,3,2,2,1,65.11628,25,9,2020,3
2,1,2,1,3,3,2,2,1,73.64341,24,9,2020,3
3,2,5,1,1,3,1,1,3,66.66667,9,9,2020,3
4,2,4,2,3,2,2,1,1,37.50000,24,9,2020,3

In [3]:
#Filtrar por ent
datos = datos[datos['ent'] == 7]

In [4]:
datos = datos[["cs_p13_1", "ano"]]

In [5]:
datos_agrupados = datos.groupby(["ano", "cs_p13_1"]).value_counts()
datos_agrupados = datos_agrupados.to_frame(name = "total").reset_index()#.drop("total", axis = 1)
datos_agrupados = datos_agrupados.pivot(index = "ano",columns= "cs_p13_1",values= "total").fillna(0)

In [6]:
datos_agrupados.apply(lambda x: 100 * x/x.sum(), axis = 1)

cs_p13_1          1          2          3         4
ano
2005      53.070699  23.358536  21.680594  1.890171
2006      52.816294  23.034565  21.992968  2.156173
2007      52.528926  22.928926  22.611570  1.930579
2008      50.104174  23.059345  24.329592  2.506889
2009      50.657895  23.488796  23.071912  2.781397
2010      48.612056  24.006182  24.642968  2.738794
2011      48.668451  23.923293  24.713303  2.694954
2012      46.865540  24.205348  26.128910  2.800202
2013      47.452168  25.033821  24.653740  2.860272
2014      47.663125  24.581188  25.070074  2.685614
2015      47.516253  23.480401  26.497507  2.505839
2016      48.036411  24.154746  24.856957  2.951886
2017      46.415950  24.684937  25.951857  2.947256
2018      43.574525  24.708236  28.389463  3.327776
2019      44.478159  25.178583  27.068715  3.274543
2020      42.296700  25.935308  28.474929  3.293063
2021      41.113313  25.505737  29.477904  3.903046
2022      40.016751  25.992276  29.896236  4.094737
2023      40.723391  25.570920  29.899554  3.806135
2024      41.690879  24.953560  29.892832  3.462729
2025      42.982280  26.897906  27.285542  2.834273