In [1]:
import pandas as pd 
from sklearn import tree
import matplotlib
import matplotlib.pyplot as plt
import openpyxl
datos = pd.read_csv("../databases/full_database.csv")

In [2]:
datos.head()

,cs_p13_1,eda7c,sex,e_con,rama,ambito2,emp_ppal,pos_ocu,ing_x_hrs,hrsocup,ent,ano,trim
0,1,3,1,1,3,4,2,1,52.09302,25,9,2020,3
1,1,2,1,3,3,2,2,1,65.11628,25,9,2020,3
2,1,2,1,3,3,2,2,1,73.64341,24,9,2020,3
3,2,5,1,1,3,1,1,3,66.66667,9,9,2020,3
4,2,4,2,3,2,2,1,1,37.50000,24,9,2020,3

In [3]:
#Filtrar por ent
datos = datos[datos['ent'] == 23]

In [4]:
datos = datos[["cs_p13_1", "ano"]]

In [5]:
datos_agrupados = datos.groupby(["ano", "cs_p13_1"]).value_counts()
datos_agrupados = datos_agrupados.to_frame(name = "total").reset_index()#.drop("total", axis = 1)
datos_agrupados = datos_agrupados.pivot(index = "ano",columns= "cs_p13_1",values= "total").fillna(0)

In [6]:
datos_agrupados.apply(lambda x: 100 * x/x.sum(), axis = 1)

cs_p13_1          1          2          3         4
ano
2005      60.764714  26.688103  11.708374  0.838809
2006      59.779669  25.535985  13.872947  0.811399
2007      59.420772  25.252996  14.573901  0.752330
2008      58.675211  26.676882  13.714564  0.933343
2009      57.746368  27.522576  13.686690  1.044366
2010      57.254656  27.046486  14.509313  1.189545
2011      57.261712  27.366721  14.289176  1.082391
2012      55.970916  27.795780  14.905556  1.327748
2013      55.237329  28.189863  15.333870  1.238938
2014      56.109726  29.128791  13.908776  0.852707
2015      54.100615  29.723390  15.286315  0.889680
2016      53.459472  28.645875  16.852401  1.042251
2017      51.982307  29.611730  17.463958  0.942005
2018      50.102991  30.921974  17.780341  1.194694
2019      48.636040  32.007591  18.114968  1.241401
2020      48.484387  31.089109  19.086062  1.340442
2021      46.913234  31.465396  20.565985  1.055384
2022      45.538212  32.328792  20.761527  1.371470
2023      45.555917  32.085300  20.877421  1.481361
2024      45.284773  32.524928  20.846713  1.343586
2025      43.408764  34.024784  21.138649  1.427802